CREATE TABLE produto (
    id BIGINT PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    QUANTIDADE BIGINT NOT NULL
);
INSERT INTO produto (1,nome, quantidade) VALUES ('Arroz', 50);
INSERT INTO produto (2,nome, quantidade) VALUES ('Feijão', 50);
INSERT INTO produto (3,nome, quantidade) VALUES ('Açúcar', 50);
INSERT INTO produto (4,nome, quantidade) VALUES ('Farinha de milho', 50);
INSERT INTO produto (5,nome, quantidade) VALUES ('Azeite de oliva', 50);
INSERT INTO produto (6,nome, quantidade) VALUES ('Pimenta', 50);
INSERT INTO produto (8,nome, quantidade) VALUES ('Espinafre', 50);
INSERT INTO produto (7,nome, quantidade) VALUES ('Pão de forma', 50);
INSERT INTO produto (9,nome, quantidade) VALUES ('Leite', 50);
INSERT INTO produto (10,nome, quantidade) VALUES ('Iogurte', 50);
INSERT INTO produto (11,nome, quantidade) VALUES ('Manteiga', 50);
INSERT INTO produto (12,nome, quantidade) VALUES ('Maionese', 50);
INSERT INTO produto (13,nome, quantidade) VALUES ('Mostarda', 50);
INSERT INTO produto (14,nome, quantidade) VALUES ('Coca-cola', 50);
INSERT INTO produto (15,nome, quantidade) VALUES ('Pasta de dente', 50);
INSERT INTO produto (16,nome, quantidade) VALUES ('Requeijão', 50);
INSERT INTO produto (17,nome, quantidade) VALUES ('Café', 50);
INSERT INTO produto (18,nome, quantidade) VALUES ('Macarrão', 50);
INSERT INTO produto (19,nome, quantidade) VALUES ('Farinha de trigo', 50);
INSERT INTO produto (20,nome, quantidade) VALUES ('Óleo de soja', 50);
INSERT INTO produto (21,nome, quantidade) VALUES ('Sal', 50);
INSERT INTO produto (22,nome, quantidade) VALUES ('Cebola', 50);
INSERT INTO produto (23,nome, quantidade) VALUES ('Batata', 50);
INSERT INTO produto (24,nome, quantidade) VALUES ('Cenoura', 50);
INSERT INTO produto (25,nome, quantidade) VALUES ('Tomate', 50);
INSERT INTO produto (26,nome, quantidade) VALUES ('Alface', 50);
INSERT INTO produto (27,nome, quantidade) VALUES ('Queijo mussarela', 50);
INSERT INTO produto (28,nome, quantidade) VALUES ('Presunto', 50);
INSERT INTO produto (29,nome, quantidade) VALUES ('Ovo', 50);
INSERT INTO produto (30,nome, quantidade) VALUES ('Ket-chup', 50);
INSERT INTO produto (31,nome, quantidade) VALUES ('Requeijão', 50);
INSERT INTO produto (32,nome, quantidade) VALUES ('Chá (mate)', 50);
INSERT INTO produto (33,nome, quantidade) VALUES ('Achocolatado', 50);
INSERT INTO produto (34,nome, quantidade) VALUES ('Suco de laranja', 50);
INSERT INTO produto (35,nome, quantidade) VALUES ('Refrigerante', 50);
INSERT INTO produto (36,nome, quantidade) VALUES ('Água miner', 50);
INSERT INTO produto (37,nome, quantidade) VALUES ('Sabão em pó', 50);
INSERT INTO produto (38,nome, quantidade) VALUES ('Detergente', 50);
INSERT INTO produto (39,nome, quantidade) VALUES ('Amaciante', 50);
INSERT INTO produto (40,nome, quantidade) VALUES ('Frango (peito)', 50);
INSERT INTO produto (41,nome, quantidade) VALUES ('Carne bovina (filé)', 50);
INSERT INTO produto (42,nome, quantidade) VALUES ('Carne suína (lombo)', 50);
INSERT INTO produto (43,nome, quantidade) VALUES ('Peixe (salmão)', 50);
INSERT INTO produto (44,nome, quantidade) VALUES ('Atum enlatado', 50);
INSERT INTO produto (45,nome, quantidade) VALUES ('Sardinha enlatada', 50);
INSERT INTO produto (46,nome, quantidade) VALUES ('Milho enlatado', 50);
INSERT INTO produto (47,nome, quantidade) VALUES ('Ervilha enlatada', 50);
INSERT INTO produto (48,nome, quantidade) VALUES ('Feijão enlatado', 50);
INSERT INTO produto (49,nome, quantidade) VALUES ('Molho de tomate', 50);
INSERT INTO produto (50,nome, quantidade) VALUES ('Ketchup', 50);
INSERT INTO produto (51,nome, quantidade) VALUES ('Papel higiênico', 50);
