INSERT INTO produto (id, nome, quantidade) VALUES
                    (1, 'Arroz', 50)                 (25, 'Feijão', 50),
                    (2, 'Macarrão', 50),             (26, 'Açúcar', 50),
                    (3, 'Farinha de trigo', 50),     (27, 'Farinha de milho', 50),
                    (4, 'Óleo de soja', 50),         (28, 'Azeite de oliva', 50),
                    (5, 'Sal', 50),                  (29, 'Pimenta', 50),
                    (6, 'Cebola', 50),               (30, 'Espinafre', 50),
                    (7, 'Batata', 50),               (31, 'Pão de forma', 50),
                    (8, 'Cenoura', 50),              (32, 'Leite', 50),
                    (9, 'Tomate', 50),               (33, 'Iogurte', 50),
                    (10, 'Alface', 50),              (34, 'Manteiga', 50),
                    (11, 'Queijo mussarela', 50),    (35, 'Maionese', 50),
                    (12, 'Presunto', 50),            (36, 'Mostarda', 50),
                    (13, 'Ovo', 50),                 (37, 'Maionese', 50),
                    (14, 'Frango (peito)', 50),      (38, 'Mostarda', 50),
                    (15, 'Carne bovina (filé)', 50), (39, 'Requeijão', 50),
                    (16, 'Carne suína (lombo)', 50), (40, 'Café', 50),
                    (17, 'Peixe (salmão)', 50),      (41, 'Chá (mate)', 50),
                    (18, 'Atum enlatado', 50),       (42, 'Achocolatado', 50),
                    (19, 'Sardinha enlatada', 50),   (43, 'Suco de laranja', 50),
                    (20, 'Milho enlatado', 50),      (44, 'Refrigerante', 50),
                    (21, 'Ervilha enlatada', 50),    (45, 'Água miner', 50),
                    (22, 'Feijão enlatado', 50),     (46, 'Sabão em pó', 50),
                    (23, 'Molho de tomate', 50),     (47, 'Detergente', 50),
                    (24, 'Ketchup', 50),             (48, 'Amaciante', 50),
                    (49, 'Papel higiênico', 50),     (50, 'Pasta de dente', 50),
